/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    gallery: Gallery;
    orders: Order;
    projects: Project;
    subscribers: Subscriber;
    'horeca-inquiries': HorecaInquiry;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'horeca-inquiries': HorecaInquiriesSelect<false> | HorecaInquiriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'care-page': CarePage;
    'about-page': AboutPage;
    'horeca-page': HorecaPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'care-page': CarePageSelect<false> | CarePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'horeca-page': HorecaPageSelect<false> | HorecaPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * URL обложки категории
   */
  image?: string | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Изделия каталога.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Как отображается на сайте. Напр.: «Ваза „Тишина“».
   */
  name: string;
  /**
   * Адрес страницы. Генерируется из названия автоматически.
   */
  slug: string;
  category?: (number | null) | Category;
  /**
   * На сайте показывается с приставкой «от». Можно менять при разговоре с клиентом.
   */
  price: number;
  /**
   * Если снять — на сайте появится бейдж «Нет в наличии», заказ через форму всё равно возможен.
   */
  inStock?: boolean | null;
  /**
   * Не больше 4–5 одновременно — это лицо сайта.
   */
  featured?: boolean | null;
  /**
   * 1–2 предложения, видны в карточке каталога.
   */
  short_description?: string | null;
  /**
   * Каждая строка → отдельный пункт списка на странице товара.
   */
  description?: string | null;
  /**
   * Маленький рассказ — как родилась форма, что особенного. Клиенту это важнее размеров.
   */
  story?: string | null;
  sort_order?: number | null;
  /**
   * Приоритетны. Первое — главное изображение.
   */
  photos?: (number | Media)[] | null;
  images?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Строки — можно писать диапазоны, напр. «6–10 см».
   */
  sizes?: {
    height?: string | null;
    diameter?: string | null;
    volume?: string | null;
  };
  /**
   * Напр.: «Шамот · обжиг 1230°C».
   */
  material?: string | null;
  /**
   * Что можно и нельзя: посудомойка, микроволновка, температура.
   */
  care?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  /**
   * Приоритетно над URL ниже
   */
  photo?: (number | null) | Media;
  /**
   * Используется, если не загружено фото
   */
  image?: string | null;
  description?: string | null;
  size?: ('normal' | 'wide' | 'tall') | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки на индивидуальный заказ с формы сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  product?: (number | null) | Product;
  type?: ('vase' | 'bowl' | 'plate' | 'mug' | 'set' | 'decor' | 'other') | null;
  purpose?: ('self' | 'gift' | 'interior' | 'unsure') | null;
  deadline?: ('flexible' | 'month' | 'date' | 'discuss') | null;
  budget?: ('lt3k' | '3k_7k' | '7k_15k' | 'gt15k' | 'unknown') | null;
  /**
   * Фото в Instagram, Pinterest и т.п.
   */
  referenceLink?: string | null;
  message: string;
  status?: ('new' | 'in-progress' | 'done') | null;
  /**
   * Клиент это не увидит. Например: позвонить в субботу, переслать ссылку на похожее.
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Реализованные заказы и коллекции для портфолио.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Напр.: «Norra · посуда для тейстинга».
   */
  title: string;
  /**
   * Адрес страницы. Генерируется из названия автоматически.
   */
  slug: string;
  /**
   * Напр.: 2026.
   */
  year?: string | null;
  type?: ('restaurant' | 'private' | 'collection' | 'cafe') | null;
  /**
   * Краткая строка под заголовком: объём, формы, материал.
   */
  subtitle?: string | null;
  description?: string | null;
  featured?: boolean | null;
  sort_order?: number | null;
  /**
   * Приоритетно над URL ниже.
   */
  mainPhoto?: (number | null) | Media;
  mainImage?: string | null;
  gallery?:
    | {
        photo?: (number | null) | Media;
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Пары «параметр — значение»: заведение, объём, материал, срок.
   */
  facts?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  quoteAuthor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Подписки на дневник мастерской.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  source?: ('journal' | 'order') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки от заведений (рестораны, кафе, бары).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horeca-inquiries".
 */
export interface HorecaInquiry {
  id: number;
  venueName: string;
  city?: string | null;
  name: string;
  /**
   * Шеф, бренд-шеф, закупщик…
   */
  position?: string | null;
  email: string;
  phone?: string | null;
  projectType?: ('new' | 'update' | 'expand' | 'scouting') | null;
  batchSize?: ('lt50' | '50_150' | '150_300' | 'gt300' | 'unknown') | null;
  timeline?: ('flexible' | 'quarter' | 'opening' | 'discuss') | null;
  /**
   * Тейстинг, фарм-ту-тэйбл, японский бар…
   */
  conceptDescription?: string | null;
  status?: ('new' | 'in-progress' | 'done') | null;
  /**
   * Клиент это не увидит. Например: позвонить в пятницу, прислать кейс Norra.
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Свободные текстовые страницы (доставка, контакты и т.п.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Адрес страницы. Генерируется из названия автоматически.
   */
  slug: string;
  /**
   * Маленький текст под заголовком. Опционально.
   */
  subtitle?: string | null;
  /**
   * Абзацы разделять пустой строкой. URL-ы превратятся в ссылки автоматически.
   */
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'horeca-inquiries';
        value: number | HorecaInquiry;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  price?: T;
  inStock?: T;
  featured?: T;
  short_description?: T;
  description?: T;
  story?: T;
  sort_order?: T;
  photos?: T;
  images?:
    | T
    | {
        url?: T;
        id?: T;
      };
  sizes?:
    | T
    | {
        height?: T;
        diameter?: T;
        volume?: T;
      };
  material?: T;
  care?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  photo?: T;
  image?: T;
  description?: T;
  size?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  product?: T;
  type?: T;
  purpose?: T;
  deadline?: T;
  budget?: T;
  referenceLink?: T;
  message?: T;
  status?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  year?: T;
  type?: T;
  subtitle?: T;
  description?: T;
  featured?: T;
  sort_order?: T;
  mainPhoto?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        photo?: T;
        image?: T;
        id?: T;
      };
  facts?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  quote?: T;
  quoteAuthor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horeca-inquiries_select".
 */
export interface HorecaInquiriesSelect<T extends boolean = true> {
  venueName?: T;
  city?: T;
  name?: T;
  position?: T;
  email?: T;
  phone?: T;
  projectType?: T;
  batchSize?: T;
  timeline?: T;
  conceptDescription?: T;
  status?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Приоритетно над URL ниже
   */
  heroPhoto?: (number | null) | Media;
  heroImage?: string | null;
  titleLine1?: string | null;
  titleLine2?: string | null;
  primaryBtnText?: string | null;
  primaryBtnLink?: string | null;
  outlineBtnText?: string | null;
  outlineBtnLink?: string | null;
  collectionSubtitle?: string | null;
  collectionHeading?: string | null;
  /**
   * Приоритетно над URL ниже
   */
  aboutPhoto?: (number | null) | Media;
  aboutImage?: string | null;
  aboutSubtitle?: string | null;
  aboutHeadingLine1?: string | null;
  aboutHeadingLine2?: string | null;
  aboutParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutCtaText?: string | null;
  aboutCtaLink?: string | null;
  processSubtitle?: string | null;
  processHeading?: string | null;
  processSteps?:
    | {
        label: string;
        /**
         * Приоритетно над URL ниже
         */
        photo?: (number | null) | Media;
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  popularSubtitle?: string | null;
  popularHeading?: string | null;
  popularCtaText?: string | null;
  popularCtaLink?: string | null;
  /**
   * Приоритетно над URL ниже
   */
  atmosphericPhoto?: (number | null) | Media;
  atmosphericImage?: string | null;
  atmosphericText?: string | null;
  gallerySubtitle?: string | null;
  galleryHeading?: string | null;
  ctaSubtitle?: string | null;
  ctaHeading?: string | null;
  ctaBtnText?: string | null;
  ctaBtnLink?: string | null;
  instaSubtitle?: string | null;
  instaHeading?: string | null;
  instaImages?:
    | {
        /**
         * Приоритетно над URL ниже
         */
        photo?: (number | null) | Media;
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "care-page".
 */
export interface CarePage {
  id: number;
  /**
   * Маленькая подпись над основным заголовком, напр. «Уход».
   */
  subtitle?: string | null;
  title?: string | null;
  /**
   * 1–2 предложения вступления под заголовком.
   */
  lead?: string | null;
  /**
   * Порядок задаётся перетаскиванием. Номера 01, 02, … подставляются автоматически.
   */
  items?:
    | {
        heading: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    /**
     * Можно оставить пустым — блок не покажется.
     */
    text?: string | null;
    /**
     * Напр. «Напишите мне».
     */
    linkText?: string | null;
    /**
     * Напр. /order или mailto:…
     */
    linkHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  /**
   * Если пусто — используется фото с alt=aeva-about-0 из Media.
   */
  portraitPhoto?: (number | null) | Media;
  /**
   * Без кавычек — они добавятся автоматически.
   */
  quoteText?: string | null;
  quoteAuthor?: string | null;
  materialPhoto?: (number | null) | Media;
  /**
   * Напр. «Материал».
   */
  materialSubtitle?: string | null;
  materialHeading?: string | null;
  materialParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  triptych?:
    | {
        photo: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Напр. «Что я делаю».
   */
  typesSubtitle?: string | null;
  typesHeading?: string | null;
  /**
   * Номера 01, 02, … подставляются автоматически.
   */
  types?:
    | {
        heading: string;
        text: string;
        /**
         * Напр. «Каталог →».
         */
        ctaText?: string | null;
        /**
         * Напр. /catalog.
         */
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Напр. «Поговорим».
   */
  ctaSubtitle?: string | null;
  ctaHeadingLine1?: string | null;
  ctaHeadingLine2?: string | null;
  ctaBtnText?: string | null;
  ctaBtnLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horeca-page".
 */
export interface HorecaPage {
  id: number;
  heroBgPhoto?: (number | null) | Media;
  heroBgUrl?: string | null;
  /**
   * Напр. «Для ресторанов и кафе».
   */
  heroMeta?: string | null;
  heroTitle?: string | null;
  heroLead?: string | null;
  heroBtnText?: string | null;
  metrics?:
    | {
        /**
         * Напр.: «12+», «50–500», «8–14», «Шамот».
         */
        value: string;
        /**
         * Напр.: «заведений по России».
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Напр. «Кейсы».
   */
  casesSubtitle?: string | null;
  casesHeading?: string | null;
  /**
   * Напр. «Как работаем».
   */
  processSubtitle?: string | null;
  processHeading?: string | null;
  /**
   * Номера 01, 02, … автоматические по порядку.
   */
  steps?:
    | {
        heading: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Напр. «Расскажите о проекте».
   */
  formSubtitle?: string | null;
  formHeading?: string | null;
  formLead?: string | null;
  formBtnText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroPhoto?: T;
  heroImage?: T;
  titleLine1?: T;
  titleLine2?: T;
  primaryBtnText?: T;
  primaryBtnLink?: T;
  outlineBtnText?: T;
  outlineBtnLink?: T;
  collectionSubtitle?: T;
  collectionHeading?: T;
  aboutPhoto?: T;
  aboutImage?: T;
  aboutSubtitle?: T;
  aboutHeadingLine1?: T;
  aboutHeadingLine2?: T;
  aboutParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  aboutCtaText?: T;
  aboutCtaLink?: T;
  processSubtitle?: T;
  processHeading?: T;
  processSteps?:
    | T
    | {
        label?: T;
        photo?: T;
        image?: T;
        id?: T;
      };
  popularSubtitle?: T;
  popularHeading?: T;
  popularCtaText?: T;
  popularCtaLink?: T;
  atmosphericPhoto?: T;
  atmosphericImage?: T;
  atmosphericText?: T;
  gallerySubtitle?: T;
  galleryHeading?: T;
  ctaSubtitle?: T;
  ctaHeading?: T;
  ctaBtnText?: T;
  ctaBtnLink?: T;
  instaSubtitle?: T;
  instaHeading?: T;
  instaImages?:
    | T
    | {
        photo?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "care-page_select".
 */
export interface CarePageSelect<T extends boolean = true> {
  subtitle?: T;
  title?: T;
  lead?: T;
  items?:
    | T
    | {
        heading?: T;
        text?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        text?: T;
        linkText?: T;
        linkHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  portraitPhoto?: T;
  quoteText?: T;
  quoteAuthor?: T;
  materialPhoto?: T;
  materialSubtitle?: T;
  materialHeading?: T;
  materialParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  triptych?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  typesSubtitle?: T;
  typesHeading?: T;
  types?:
    | T
    | {
        heading?: T;
        text?: T;
        ctaText?: T;
        ctaLink?: T;
        id?: T;
      };
  ctaSubtitle?: T;
  ctaHeadingLine1?: T;
  ctaHeadingLine2?: T;
  ctaBtnText?: T;
  ctaBtnLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horeca-page_select".
 */
export interface HorecaPageSelect<T extends boolean = true> {
  heroBgPhoto?: T;
  heroBgUrl?: T;
  heroMeta?: T;
  heroTitle?: T;
  heroLead?: T;
  heroBtnText?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  casesSubtitle?: T;
  casesHeading?: T;
  processSubtitle?: T;
  processHeading?: T;
  steps?:
    | T
    | {
        heading?: T;
        text?: T;
        id?: T;
      };
  formSubtitle?: T;
  formHeading?: T;
  formLead?: T;
  formBtnText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}